# General
title: Luke Fretwell
description: "Entrepreneur, writer, civic hacker focused on the intersection of democracy and technology."
avatar: avatar.png
url: https://lukefretwell.com

# Social
email: mailto:luke@lukefretwell.com
calendar: https://lukefretwell.com/calendar
twitter: https://twitter.com/lukefretwell
linkedin: https://www.linkedin.com/in/lukefretwell
github: https://github.com/lukefretwell
rss: https://lukefretwell.com/feed.xml

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-assets

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Date/time
date: "%B %-d, %Y"
timezone: America/Los_Angeles

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "work"
    values:
      layout: "work"

# Collections
collections:
  pages:
    output: true
    permalink: /:title
  posts:
    output: true
    permalink: /posts/:title
  work:
    output: true
    permalink: /work/:title

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
  - .sass-cache
  - .DS_Store
  - .gitignore
  - .jekyll-metadata
  - .env
  - config.local.yml
  - config.production.yml
