# General
title: Luke Fretwell
description: ""
avatar: profile.png
url: https://lukefretwell.com

# Social

email: mailto:luke@lukefretwell.com
twitter: https://twitter.com/lukefretwell
linkedin: https://www.linkedin.com/in/lukefretwell
github: https://github.com/lukefretwell


social:
  name: Luke Fretwell
  links:
    - https://twitter.com/lukefretwell
    - https://www.linkedin.com/in/lukefretwell
    - https://github.com/lukefretwell

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

kramdown:
  auto_ids: true

# Date/time
date: "%B %-d, %Y"
timezone: America/Los_Angeles

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "work"
    values:
      layout: "work"
  - scope:
      path: ""
      type: "category"
    values:
      layout: "category"

collections:
  pages:
    output: true
    permalink: :title
  posts:
    output: true
    permalink: /posts/:title
  work:
    output: true
    permalink: /work/:title
  categories:
    output: true
    permalink: categories/:title

# Exclude
exclude:
  - CNAME
  - readme.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
