docs_list_title: services
docs:

  - title: Advice
    description: Strategic, tactical
    icon: fa-brain
    url: "#advice"
    tags: 
      - Board advisory
      - Startup guidance
      - Business strategy
      - Executive mentorship
      - One-on-one and team coaching

  - title: Product
    description: Plan, deliver
    icon: fa-rocket
    url: "#product"
    tags: 
      - Strategy
      - Design
      - Development
      - Launch

  - title: Brand
    description: Image, identity
    icon: fa-wand-magic-sparkles
    url: "#brand"
    tags: 
      - Naming
      - Positioning
      - Visual identity

  - title: Narrative
    description: Comms, content
    icon: fa-comment
    url: "#narrative"
    tags: 
      - Content strategy and implementation
      - Media positioning and coaching
