docs_list_title: services
docs:

  - title: Advice
    description: Strategic, tactical
    icon: fa-brain
    url: "#advisory"

  - title: Product
    description: Plan, deliver
    icon: fa-rocket
    url: "#project-and-strategy"

  - title: Brand
    description: Image, identity
    icon: fa-wand-magic-sparkles
    url: "#brand"

  - title: Narrative
    description: Comms, content
    icon: fa-comment
    url: "#narrative-and-communications"
